spring:
  application:
    name: jonesun-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false

    sentinel:
      transport:
        dashboard: localhost:8105  #sentinel的图形化界面访问路径
        port: 8719
      scg:
        fallback: #服务降级返回的响应结果
          mode: reponse
          response-status: 426
          response-body: error request

    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true  #开启表示根据微服务名称映射，就是微服务名称拼接到url中可以直接访问，但是不推荐这么使用 容易暴露微服务
          lower-case-service-id: true #使用小写service-id
      enabled: true #默认开启网关true，关闭网关false

      routes:
        # 路由标识
        - id: jonesun-user-api
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://jonesun-user-api
          # 路由条件
          predicates:
            # 转发地址格式
            - Path=/api/**
          # 截取路径位数
          filters:
            - StripPrefix= 1
#        - id: oauth2-resource-route
#          uri: lb://oauth2-resource
#          predicates:
#            - Path=/resource/**
#          filters:
#            - StripPrefix=1
        - id: oauth2-auth-route
          uri: lb://jonesun-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: oauth2-auth-login
          uri: lb://jonesun-oauth2-auth
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: oauth2-auth-token
          uri: lb://jonesun-oauth2-auth
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: oauth2-auth-authorize
          uri: lb://jonesun-oauth2-auth
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8106/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: 123456
secure:
  ignore:
    urls: # 配置白名单路径
      - "/actuator/**"
      - "/oauth/token"
      - "/oauth/authorize"
      - "/login"
      - "/jonesun-user-api/api/hello"
server:
  port: 8102
feign:
  sentinel:
    enabled: true