server:
  port: 8106
spring:
  profiles:
    active: dev
  application:
    name: jonesun-oauth2-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"


#  # h2配置(日常开发改为mysql配置即可)
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: test
#  h2:
#    console:
#      enabled: true
#      path: /console
