spring:
  application:
    name: jonesun-admin
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8101

